# Generated by Django 5.2.7 on 2025-10-25 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_r_us', '0002_skill_event_volunteerprofile_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_id', models.CharField(max_length=64)),
                ('volunteer_name', models.CharField(blank=True, max_length=255)),
                ('event_id', models.CharField(max_length=64)),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('attended', 'Attended'), ('no_show', 'No-Show'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('notify', models.BooleanField(default=False)),
                ('override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('match_score', models.FloatField(default=0)),
                ('match_reason', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_id', 'status'], name='volunteers__event_i_23c3ff_idx'), models.Index(fields=['volunteer_id'], name='volunteers__volunte_72def7_idx')],
                'unique_together': {('volunteer_id', 'event_id')},
            },
        ),
    ]
