# Generated by Django 5.2.7 on 2025-10-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_r_us', '0003_assignment'),
        ('volunteers_r_us', '0004_profile'),
    ]

    operations = [
    ]
