# Generated by Django 5.2.7 on 2025-10-31 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_r_us', '0005_merge_0003_assignment_0004_profile'),
    ]

operations = [
    # remove old indexes first
    migrations.RemoveIndex(
        model_name='assignment',
        name='volunteers__event_i_23c3ff_idx',
    ),
    migrations.RemoveIndex(
        model_name='assignment',
        name='volunteers__volunte_72def7_idx',
    ),
    migrations.AlterUniqueTogether(name='assignment', unique_together=set()),
    migrations.AlterUniqueTogether(name='match', unique_together=set()),

    # 🔹 move these two up BEFORE adding new fields
    migrations.RemoveField(
        model_name='assignment',
        name='event_id',
    ),
    migrations.RemoveField(
        model_name='assignment',
        name='volunteer_id',
    ),

    # now safe to add the new foreign keys
    migrations.AddField(
        model_name='assignment',
        name='event',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='assignments',
            to='volunteers_r_us.event',
        ),
    ),
    migrations.AddField(
        model_name='assignment',
        name='volunteer',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='assignments',
            to=settings.AUTH_USER_MODEL,
        ),
    ),

    migrations.AddField(
        model_name='event',
        name='updated_at',
        field=models.DateTimeField(auto_now=True),
    ),
    migrations.AlterField(
        model_name='assignment',
        name='created_by',
        field=models.ForeignKey(
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='created_assignments',
            to=settings.AUTH_USER_MODEL,
        ),
    ),
    migrations.AlterField(
        model_name='event',
        name='location',
        field=models.CharField(max_length=255),
    ),
    migrations.AlterField(
        model_name='event',
        name='required_skills',
        field=models.ManyToManyField(blank=True, related_name='events', to='volunteers_r_us.skill'),
    ),
    migrations.AlterField(
        model_name='event',
        name='urgency',
        field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
    ),
    migrations.AlterField(
        model_name='match',
        name='event',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers_r_us.event'),
    ),
    migrations.AlterField(
        model_name='skill',
        name='name',
        field=models.CharField(max_length=100, unique=True),
    ),
    migrations.AddIndex(
        model_name='assignment',
        index=models.Index(fields=['event', 'status'], name='volunteers__event_i_23c3ff_idx'),
    ),
    migrations.AddIndex(
        model_name='assignment',
        index=models.Index(fields=['volunteer'], name='volunteers__volunte_72def7_idx'),
    ),
    migrations.AddConstraint(
        model_name='assignment',
        constraint=models.UniqueConstraint(fields=('volunteer', 'event'), name='uq_assignment_volunteer_event'),
    ),
    migrations.AddConstraint(
        model_name='match',
        constraint=models.UniqueConstraint(fields=('volunteer', 'event'), name='uq_match_volunteer_event'),
    ),
]
