# Generated by Django 5.2.7 on 2025-10-31 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_r_us', '0008_add_event_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteers_r_us.event'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
