# Generated by Django 5.2.7 on 2025-10-22 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [('notify','0001_initial')]
    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='notifications',
                to=settings.AUTH_USER_MODEL,
                default=1,   # <-- use 1
            ),
            preserve_default=False,
        ),
    ]
