# Generated by Django 5.2.7 on 2025-10-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alter_notification_options_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
